language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest -v --cov=filestack tests

notifications:
  email:
    recipients:
      - dev@filestack.com
    on_success: never
    on_failure: always

after_success:
  - coveralls
